config/routes.rb
Wincent::Application.routes.draw do
  get ':id',
    id: ShortLink::SHORT_LINK_REGEX,
    constraints: { domain: APP_CONFIG['short_link_host'] },
    to: 'short_links#show'

  # must explicitly allow period in the id part of the route
  # otherwise it will be classified as a route separator
  resources :articles, id: /[^\/]+/ , path: 'wiki' do
    collection do
      get 'page/:page' => 'articles#index', :page => %r{\d+}
    end
  end

  resources :comments, except: %i[create new update]

  resources :links

  # must explicitly allow period in the id part of the route otherwise it
  # will be classified as a route separator
  resources :posts, path: 'blog', id: /[a-z0-9\-\.]+/ do
    collection do
      get 'page/:page' => 'posts#index', :page => %r{\d+}
    end
  end

  get 'repos', to: redirect('https://github.com/wincent')
  get 'repos/*rest', to: redirect('https://github.com/wincent')

  resources :resets
  resources :sessions, only: %i[new create destroy]

  resources :snippets do
    collection do
      get 'page/:page' => 'snippets#index', :page => %r{\d+}
    end
  end

  resources :taggings

  # must explicitly allow period in the id part of the route otherwise
  # it will be classified as a route separator
  resources :tags, id: /[a-z0-9\.]+/ do
    collection do
      get :search
    end
  end

  get 'twitter', to: redirect(APP_CONFIG['twitter_url'])
  get 'twitter/*rest', to: redirect(APP_CONFIG['twitter_url'])

  resources :users, only: %i[index show] do
    resources :emails, id: /[^\/]+/
  end

  get 'dashboard', to: redirect('/')
  get 'heartbeat/ping'

  get 'l/:id'           => 'links#show'
  get 'login'           => 'sessions#new'
  get 'logout'          => 'sessions#destroy'
  get 'misc/:action'    => 'misc'
  get 'search', to: redirect('https://www.google.com/#q=site:wincent.com')
  get 'support', to: redirect('/issues')

  root :to => 'posts#index'
end

app/models/snippet.rb
# Schema:
#
#   string   "description"
#   integer  "markup_type",       :default => 0
#   text     "body"
#   datetime "created_at"
#   datetime "updated_at"
#   boolean  "public",            :default => true
#   integer  "comments_count",    :default => 0
#   boolean  "accepts_comments",  :default => true
#
class Snippet < ActiveRecord::Base
  module MarkupType
    # base types
    WIKITEXT    = 0
    PLAINTEXT   = 1
    HTML        = 2

    # syntax-highlighted types
    C           = 100
    DIFF        = 200
    OBJECTIVE_C = 300
    RUBY        = 400
    SHELL       = 500
  end

  MARKUP_TYPES = Hash.new(0).merge!({
    'Wikitext'    => MarkupType::WIKITEXT,
    'Plain text'  => MarkupType::PLAINTEXT,
    'HTML'        => MarkupType::HTML,
    'C'           => MarkupType::C,
    'Diff'        => MarkupType::DIFF,
    'Objective-C' => MarkupType::OBJECTIVE_C,
    'Ruby'        => MarkupType::RUBY,
    'Shell'       => MarkupType::SHELL
  }).freeze

  acts_as_taggable

  attr_accessible :accepts_comments, :body, :description, :markup_type,
    :pending_tags, :public

  belongs_to :last_commenter, class_name: 'User'

  has_many  :comments,
            -> { includes(:user).order('comments.created_at') },
            as:        :commentable,
            extend:    Commentable,
            dependent: :destroy

  scope :published, -> { where(public: true) }
  scope :recent,    -> { published.order('updated_at DESC').limit(10) }

  validates_presence_of :body
  validates_inclusion_of :markup_type,
    in:      MARKUP_TYPES.values,
    message: 'not a valid markup type'

  def body_html options = {}
    case markup_type
    when MarkupType::WIKITEXT
      body.w options
    when MarkupType::PLAINTEXT
      escape_and_wrap_body
    when MarkupType::HTML
      body.html_safe
    when MarkupType::C
      escape_and_wrap_body 'c'
    when MarkupType::DIFF
      escape_and_wrap_body 'diff'
    when MarkupType::OBJECTIVE_C
      escape_and_wrap_body 'objc'
    when MarkupType::RUBY
      escape_and_wrap_body 'ruby'
    when MarkupType::SHELL
      escape_and_wrap_body 'shell'
    else # unlikely to get here (due to validations)
      raise "Unknown markup type #{markup_type}"
    end
  end

private

  include ERB::Util

  def escape_and_wrap_body lang = nil
    if lang
      %Q{<pre class="#{lang}-syntax">#{h body}</pre>\n}
    else
      %Q{<pre>#{h body}</pre>\n}
    end.html_safe
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_filter :require_admin, :except => [ :index, :show ]
  before_filter :get_published_snippet, :only => :show
  before_filter :get_snippet, :only => [ :edit, :update, :destroy ]

  def index
    respond_to do |format|
      format.html {
        @paginator = RestfulPaginator.new params, Snippet.published.count,
          snippets_path, 10
        @snippets = Snippet.recent.offset @paginator.offset
      }
    end
  end

  # Admin only.
  def new
    @snippet = Snippet.new
  end

  # Admin only.
  def create
    if request.xhr? # live preview
      @snippet = Snippet.new :body => params[:body],
        :description => params[:description],
        :markup_type => params[:markup_type]
      render :partial => 'preview'
    else # normal request
      @snippet = Snippet.new params[:snippet]
      if @snippet.save
        flash[:notice] = 'Successfully created new snippet'
        redirect_to @snippet
      else
        flash[:error] = 'Failed to create new snippet'
        render :action => 'new'
      end
    end
  end

  def show
    # BUG: this comments association is not a lazy ActiveRelation query like I had hoped
    @comments = @snippet.comments.published
    respond_to do |format|
      format.html {
        @comment = @snippet.comments.new if @snippet.accepts_comments?
      }
      format.text { render text: @snippet.body }
    end
  end

  # Admin only.
  def edit
    render
  end

  # Admin only.
  def update
    if @snippet.update_attributes params[:snippet]
      flash[:notice] = 'Successfully updated'
      redirect_to @snippet
    else
      flash[:error] = 'Update failed'
      render :action => :edit
    end
  end

  # Admin only.
  def destroy
    @snippet.destroy
    flash[:notice] = 'Successfully destroyed'
    redirect_to snippets_path
  end

private

  def get_snippet
    @snippet = Snippet.find params[:id]
  end

  # TODO: due to page caching, we can't afford to let admins see private
  # snippets, so will have to add an admin namespace for listing and showing
  # can always redirect there from here for admins
  def get_published_snippet
    @snippet = Snippet.published.find params[:id]
  end

  def record_not_found
    super snippets_path
  end
end

app/views/snippets/_form.html.haml
%h1.major= @page_title
= render 'shared/error_messages', model: @snippet
= form_for @snippet do |f|
  = f.text_field :description, annotation: 'optional'
  = f.text_area :body, rows: 20
  = f.select :markup_type, Snippet::MARKUP_TYPES, label: 'Markup'
  = f.text_field :pending_tags, label: 'Tags'
  = f.check_box :public
  = f.check_box :accepts_comments
  = f.submit
%h2#preview_link.major Preview
#ajax-flash
#preview= render 'preview'
- content_for :javascript do
  :javascript
    Wincent.Snippets.init();
    Wincent.Ajax.observeField({
      kind:      'snippet',
      fieldName: 'body',
      include:   ['description', 'markup_type'],
      url:       '#{snippets_path}'
    });
    Wincent.Ajax.observeField({
      kind:      'snippet',
      fieldName: 'description',
      include:   ['body', 'markup_type'],
      url:       '#{snippets_path}'
    });
    Wincent.Ajax.observeField({
      kind:      'snippet',
      fieldName: 'markup_type',
      include:   ['body', 'description'],
      url:       '#{snippets_path}'
    });
    Wincent.Ajax.setupPreviewLink({
      kind:    'snippet',
      include: ['body', 'description', 'markup_type'],
      url:     '#{snippets_path}'
    });

app/views/snippets/_preview.html.haml
%h3 Snippet preview
%h4=snippet_title @snippet
=@snippet.body_html :base_heading_level => 4

app/views/snippets/_snippet.html.haml
%div[snippet]
  %h2=link_to snippet_title(snippet), snippet_path(snippet)
  %div.info
    %span.when= link_to timeinfo(snippet), snippet
  =snippet.body_html base_heading_level: 3

app/views/snippets/edit.html.haml
- @page_title = 'Edit snippet'
= breadcrumbs link_to('Snippets', snippets_path),
  link_to(snippet_title(@snippet), @snippet),
  @page_title
= render 'form'
.links
  = link_to 'show', @snippet
  = link_to 'all snippets', snippets_path

app/views/snippets/index.html.haml
=breadcrumbs 'Snippets'
=render @snippets
=@paginator.pagination_links

app/views/snippets/new.html.haml
- @page_title = 'New snippet'
= breadcrumbs link_to('Snippets', snippets_path), @page_title
= render 'form'
.links=link_to 'index', snippets_path

app/views/snippets/show.html.haml
= breadcrumbs link_to('Snippets', snippets_path), snippet_title(@snippet)
%h1.major= snippet_title @snippet
%div[@snippet]
  .when
    = timeinfo @snippet
    by
    = mail_to APP_CONFIG['admin_email'], APP_CONFIG['admin_name']
  = @snippet.body_html base_heading_level: 1
= render 'shared/tags', taggable: @snippet
.links
  = link_to 'raw', snippet_path(@snippet, format: :txt)
- if @snippet.accepts_comments? || @snippet.comments_count != 0
  %h3.major Comments
  %ol#comments.boxed
    = render @comments
  %h4.major Add a comment
  %p Comments are now closed for this snippet.