config/routes.rb
Wincent::Application.routes.draw do
  get ':id',
    id: ShortLink::SHORT_LINK_REGEX,
    constraints: { domain: APP_CONFIG['short_link_host'] },
    to: 'short_links#show'

  # must explicitly allow period in the id part of the route
  # otherwise it will be classified as a route separator
  resources :articles, id: /[^\/]+/ , path: 'wiki' do
    collection do
      get 'page/:page' => 'articles#index', :page => %r{\d+}
    end
  end

  resources :comments, except: %i[create new update]

  resources :links

  # must explicitly allow period in the id part of the route otherwise it
  # will be classified as a route separator
  resources :posts, path: 'blog', id: /[a-z0-9\-\.]+/ do
    collection do
      get 'page/:page' => 'posts#index', :page => %r{\d+}
    end
  end

  get 'repos', to: redirect('https://github.com/wincent')
  get 'repos/*rest', to: redirect('https://github.com/wincent')

  resources :resets
  resources :sessions, only: %i[new create destroy]

  resources :snippets do
    collection do
      get 'page/:page' => 'snippets#index', :page => %r{\d+}
    end
  end

  resources :taggings

  # must explicitly allow period in the id part of the route otherwise
  # it will be classified as a route separator
  resources :tags, id: /[a-z0-9\.]+/ do
    collection do
      get :search
    end
  end

  get 'twitter', to: redirect(APP_CONFIG['twitter_url'])
  get 'twitter/*rest', to: redirect(APP_CONFIG['twitter_url'])

  resources :users, only: %i[index show] do
    resources :emails, id: /[^\/]+/
  end

  get 'dashboard', to: redirect('/')
  get 'heartbeat/ping'

  get 'l/:id'           => 'links#show'
  get 'login'           => 'sessions#new'
  get 'logout'          => 'sessions#destroy'
  get 'misc/:action'    => 'misc'
  get 'search', to: redirect('https://www.google.com/#q=site:wincent.com')
  get 'support', to: redirect('/issues')

  root :to => 'posts#index'
end

app/models/article.rb
# This is not intended to be a community-driven wiki, so there are no author
# attributes or moderation flags (although note that article comments are
# enabled by default).
class Article < ActiveRecord::Base
  # titles may contain anything other than underscores and slashes
  TITLE_REGEX         = %r{\A[^_/]+\z}

  include Linking

  has_many                :comments,
                          -> { includes(:user).order('comments.created_at') },
                          as:         :commentable,
                          extend:     Commentable,
                          dependent:  :destroy
  belongs_to              :last_commenter, class_name: 'User'
  validates_presence_of   :title
  validates_uniqueness_of :title
  validates_format_of     :title,
                          with:    TITLE_REGEX,
                          message: 'must not contain underscores or slashes'
  validates_format_of     :redirect,
                          with: /(#{LINK_REGEX})          |
                                 (#{EXTERNAL_LINK_REGEX}) |
                                 (#{RELATIVE_PATH_REGEX})/x,
                          if: -> (a) { !a.redirect.blank? },
                          message: 'must be a valid [[wiki]] link, HTTP/HTTPS URL or relative path'
  validates_length_of     :body, maximum: 128 * 1024, allow_blank: true
  validate                :check_redirect_and_body
  attr_accessible         :title, :redirect, :body, :public, :accepts_comments, :pending_tags
  acts_as_taggable
  # TODO: acts_as_versioned attributes: %i[title redirect body]


  scope :published, -> { where(public: true) }
  scope :recent,    -> { published.order('updated_at DESC').limit(10) }

  # NOTE: MySQL will do a case-insensitive find here, so "foo" and "FOO" refer
  # to the same article
  def self.find_with_param! param, user = nil
    article = find_by_title! deparametrize(param)
    if !article.public? && (!user || !user.superuser?)
      # TODO: smell here: controller exception raised from model layer
      raise ActionController::ForbiddenError
    end
    article
  end

  def check_redirect_and_body
    if redirect.blank? && body.blank?
      errors.add :body, "can't be blank unless a redirect is supplied"
      errors.add :redirect, "can't be blank unless a body is supplied"
    end
  end

  # There are three kinds of redirects possible:
  #   1. Absolute URLs: http://example.com/ or https://example.com/
  #   2. Relative URLs: /issues/640
  #   3. Internal wiki links: [[foo]]
  # This method returns true if the receiver is an "internal wiki link"
  # redirect. We're interested in this property because we want to know when to
  # display "redirected from" annotations (which we only want for redirections
  # _within_ the wiki)
  def wiki_redirect?
    !!(self.redirect? && self.redirect =~ LINK_REGEX)
  end

  def redirection_url
    url_for_link redirect
  end

  # this is a string-to-string transformation, unlike to_param/from_param
  def self.deparametrize string
    string.gsub '_', ' '
  end

  def self.parametrize string
    string.gsub ' ', '_'
  end

  # capitalize first word only IFF it is all lowercase
  def self.smart_capitalize string
    words = string.split
    if first = words.first
      words[0] = first.capitalize if first =~ /\A[a-z]+\z/
    end
    words.join(' ')
  end

  def to_param
    param = (changes['title'] && changes['title'].first) || title
    Article.parametrize param
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_admin,   except: %i[index show]
  before_filter :get_article,     only: %i[show edit update]

  def index
    respond_to do |format|
      format.html {
        @paginator  = RestfulPaginator.new params, Article.published.count, articles_path
        @articles   = Article.recent.offset @paginator.offset
        @tags       = Article.find_top_tags
      }
    end
  end

  def show
    if @article.redirect?
      if session[:redirection_count] and session[:redirection_count] > 5
        clear_redirection_info
        flash[:error] = 'Too many redirections'
        redirect_to articles_path
      else
        if @article.wiki_redirect?
          session[:redirection_count] = session[:redirection_count] ? session[:redirection_count] + 1 : 1
          session[:redirected_from] = params[:id]
        end
        redirect_to @article.redirection_url
      end
    else # not a redirect
      if session[:redirected_from]
        @redirected_from = Article.find_with_param! session[:redirected_from], current_user
      end
      @comments = @article.comments.published
      respond_to do |format|
        format.html {
          flash[:notice] = stale_article_notice if @article.updated_at < 1.year.ago
          @comment = @article.comments.new if @article.accepts_comments?
        }
      end
      clear_redirection_info
    end
  end

  def new
    @article = Article.new session[:new_article_params]
    session[:new_article_params] = nil
  end

  def create
    if request.xhr? # live preview
      @article = Article.new :title => params[:title], :body => params[:body]
      render :partial => 'preview'
    else # normal request
      @article = Article.new params[:article]
      if @article.save
        flash[:notice] = 'Successfully created new article'
        redirect_to @article
      else
        flash[:error] = 'Failed to create new article'
        render :action => 'new'
      end
    end
  end

  def edit
    render
  end

  def update
    if @article.update_attributes params[:article]
      flash[:notice] = 'Successfully updated'
      redirect_to @article
    else
      flash[:error] = 'Update failed'
      render :action => 'edit'
    end
  end

private

  def stale_article_notice
    <<-NOTICE
      This article is over 1 year old <em>(to check for a more recent resource
      see the <a href="#{articles_path}">wiki</a> index, the
      <a href="#{tags_path}">tag cloud</a>, or the
      <a href="#{search_tags_path}">tag search</a> page)</em>
    NOTICE
  end

  def get_article
    @article = Article.find_with_param! params[:id], current_user
  rescue ActionController::ForbiddenError
    flash[:error] = forbidden_flash_message
    redirect_to articles_path
  end

  def record_not_found
    if admin?
      flash[:notice] = 'Requested article not found: create it?'
      title = Article.deparametrize params[:id]
      session[:new_article_params] = { :title => Article.smart_capitalize(title) }
      redirect_to new_article_path
    else
      super articles_path
    end
  end

  def clear_redirection_info
    session[:redirected_from]   = nil
    session[:redirection_count] = 0
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def redirected_from
    if @redirected_from
      content_tag :p do
        edit_link = if admin?
          ' [' + link_to("edit", edit_article_path(@redirected_from)) + ']'
        else
          ''
        end

        raw "(Redirected from #{h @redirected_from.title}#{edit_link})"
      end
    end
  end
end

app/views/articles/_form.html.haml
= render 'shared/error_messages', model: article

= form_for article do |f|
  = f.text_field :title
  = f.text_field :redirect, annotation: 'optional'
  = f.text_area :body, rows: 30, annotation: wikitext_cheatsheet
  = f.text_field :pending_tags, label: 'Tags'
  = f.check_box :public
  = f.check_box :accepts_comments
  = f.submit

- content_for :javascript do
  :javascript
    Wincent.Articles.init();

app/views/articles/_preview.html.haml
%h3=@article.title.w
=@article.body.w :base_heading_level => 3

app/views/articles/edit.html.haml
- @page_title = 'Edit article'
= breadcrumbs link_to('Wiki', articles_path),
  link_to(@article.title, article_path(@article)),
  @page_title
%h1.major= @page_title
= render 'form', article: @article
%h2#preview_link.major Preview
-# TODO: graceful non-JS fallback
#ajax-flash
#preview= render 'preview'
.links
  =link_to 'index', articles_path
  =link_to 'show', article_path(@article)
- content_for :javascript do
  :javascript
    Wincent.Ajax.observeField({ 'kind': 'article', 'fieldName': 'title', 'include': ['body'], 'url': '#{articles_path}' });
    Wincent.Ajax.observeField({ 'kind': 'article', 'fieldName': 'body', 'include': ['title'], 'url': '#{articles_path}' });
    Wincent.Ajax.setupPreviewLink({ 'kind': 'article', 'include': ['body', 'title'], 'url': '#{articles_path}' });

app/views/articles/index.html.haml
-@page_title = 'wiki index'
=breadcrumbs 'Wiki'
%h1 Wiki articles
%table.table
  %thead
    %tr
      %th Title
      %th When
  -# Rails BUG: https://rails.lighthouseapp.com/projects/8994/tickets/5060
  -unless @articles.load.empty?
    %tbody
    -for article in @articles
      %tr
        %td=link_to article.title, article_path(article)
        %td=timeinfo article
=@paginator.pagination_links if @paginator
%h2.major Top #{link_to 'tags', tags_path} in the wiki
.cloud
  -for tag in @tags
    =scaled_tag tag, 'article'
%h2.major Tag search
%form{'accept-charset' => 'UTF-8', :action => search_tags_path, :method => 'get'}
  %span.annotation Find items which feature <em>all</em> of the specified tags
  %br
  =text_field_tag :q, params[:q], :size => 40
  =hidden_field_tag 'type', 'article'
  %input(type='submit' value='Search')

app/views/articles/new.html.haml
- @page_title = 'New article'
= breadcrumbs link_to('Wiki', articles_path), @page_title
%h1.major= @page_title
= render 'form', article: @article
%h2#preview_link.major Preview
-# TODO: graceful non-JS fallback
#ajax-flash
  #preview= render 'preview'
%p= link_to 'index', articles_path
- content_for :javascript do
  :javascript
    Wincent.Ajax.observeField({ 'kind': 'article', 'fieldName': 'title', 'include': ['body'], 'url': '#{articles_path}' });
    Wincent.Ajax.observeField({ 'kind': 'article', 'fieldName': 'body', 'include': ['title'], 'url': '#{articles_path}' });
    Wincent.Ajax.setupPreviewLink({ 'kind': 'article', 'include': ['body', 'title'], 'url': '#{articles_path}' });

app/views/articles/show.html.haml
-@page_title = @article.title
=breadcrumbs link_to('Wiki', articles_path), @article.title
%h1.major=@article.title
.when
  =timeinfo @article
  by
  =mail_to APP_CONFIG['admin_email'], APP_CONFIG['admin_name']
=redirected_from
.article
  =@article.body.w :base_heading_level => 1
= render 'shared/tags', taggable: @article
.links
  -if admin?
    =link_to 'edit', edit_article_path(@article)
  =link_to 'wiki index', articles_path
-if @article.accepts_comments? || @article.comments_count != 0
  %h2.major Comments
  %ol#comments.boxed
    =render @comments
  %h3.major Add a comment
  %p Comments are now closed for this article.