config/routes.rb
Wincent::Application.routes.draw do
  get ':id',
    id: ShortLink::SHORT_LINK_REGEX,
    constraints: { domain: APP_CONFIG['short_link_host'] },
    to: 'short_links#show'

  # must explicitly allow period in the id part of the route
  # otherwise it will be classified as a route separator
  resources :articles, id: /[^\/]+/ , path: 'wiki' do
    collection do
      get 'page/:page' => 'articles#index', :page => %r{\d+}
    end
  end

  resources :comments, except: %i[create new update]

  resources :links

  # must explicitly allow period in the id part of the route otherwise it
  # will be classified as a route separator
  resources :posts, path: 'blog', id: /[a-z0-9\-\.]+/ do
    collection do
      get 'page/:page' => 'posts#index', :page => %r{\d+}
    end
  end

  get 'repos', to: redirect('https://github.com/wincent')
  get 'repos/*rest', to: redirect('https://github.com/wincent')

  resources :resets
  resources :sessions, only: %i[new create destroy]

  resources :snippets do
    collection do
      get 'page/:page' => 'snippets#index', :page => %r{\d+}
    end
  end

  resources :taggings

  # must explicitly allow period in the id part of the route otherwise
  # it will be classified as a route separator
  resources :tags, id: /[a-z0-9\.]+/ do
    collection do
      get :search
    end
  end

  get 'twitter', to: redirect(APP_CONFIG['twitter_url'])
  get 'twitter/*rest', to: redirect(APP_CONFIG['twitter_url'])

  resources :users, only: %i[index show] do
    resources :emails, id: /[^\/]+/
  end

  get 'dashboard', to: redirect('/')
  get 'heartbeat/ping'

  get 'l/:id'           => 'links#show'
  get 'login'           => 'sessions#new'
  get 'logout'          => 'sessions#destroy'
  get 'misc/:action'    => 'misc'
  get 'search', to: redirect('https://www.google.com/#q=site:wincent.com')
  get 'support', to: redirect('/issues')

  root :to => 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  PAGE_SIZE = 10

  has_many                :comments,
                          -> { includes(:user).order('comments.created_at') },
                          as:        :commentable,
                          extend:    Commentable,
                          dependent: :destroy
  belongs_to              :last_commenter, class_name: 'User'
  validates_presence_of   :title
  validates_format_of     :permalink,
                          with: /\A[a-z0-9\.\-]+\z/,
                          message: 'must contain only lowercase letters, numbers, periods and hyphens'
  validates_presence_of   :permalink
  validates_uniqueness_of :permalink
  validates_presence_of   :excerpt
  validates_length_of     :body, maximum: 128 * 1024, allow_blank: true
  attr_accessible         :title, :permalink, :excerpt, :body, :public,
                          :accepts_comments, :pending_tags
  before_validation       :set_permalink

  scope :published, -> { where(public: true) }
  scope :recent,    -> { published.order('created_at DESC') }
  scope :page,      -> { limit(PAGE_SIZE) }

  acts_as_taggable

  def suggested_permalink
    # iconv can't be trusted to behave the same across platforms, so don't use
    # it this doesn't handle non-ASCII characters very well (they just get
    # eaten), but for my uses it will be fine
    base = title ? title.downcase.split(/[^a-z0-9\.]+/).join('-') : ''
    if base.length == 0
      # handle pathological case
      base = id.nil? ? 'post' : id.to_s
    end

    # now need to make sure it is unique
    # there is a race here, but it is harmless for two reasons:
    # - I am the only user creating articles
    # - if the proposed permalink is not unique validation will fail and the
    #   user can correct the problem
    # worst case scenario is that validation passes and then the database-level
    # constraint kicks in
    last =  Post.where(['permalink REGEXP ?', "^#{base}(-[0-9]+)?$"]).
      order('permalink').last
    if last.nil?
      base
    else
      if last.permalink =~ /\-(\d+)$/
        num = $~[1].to_i + 1
      else
        num = 2
      end
      "#{base}-#{num}"
    end
  end

  def to_param
    (changes['permalink'] && changes['permalink'].first) || permalink
  end

private

  def set_permalink
    if permalink.blank?
      self.permalink = self.suggested_permalink
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_admin, except: %i[index show]
  before_filter :get_post,      except: %i[index new create]

  def index
    respond_to do |format|
      format.html {
        @paginator = RestfulPaginator.new(params, Post.published.count, posts_path)
        @posts     = Post.recent.includes(:tags).offset(@paginator.offset).page
      }
    end
  end

  def new
    @post = Post.new session[:new_post_params]
    session[:new_post_params] = nil
  end

  def create
    if request.xhr? # live preview
      @post = Post.new(title:   params[:title],
                       excerpt: params[:excerpt],
                       body:    params[:body])
      render partial: 'preview'
    else # normal request
      @post = Post.new params[:post]
      if @post.save
        flash[:notice] = 'Successfully created new post'
        redirect_to @post
      else
        flash[:error] = 'Failed to create new post'
        render :action => 'new'
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html {
        flash[:notice] = 'Deleted post'
        redirect_to admin_posts_path
      }
      format.js
    end
  end

  def show
    @comments = @post.comments.published
    respond_to do |format|
      format.html { @comment = @post.comments.new if @post.accepts_comments? }
    end
  end

  def edit
    render
  end

  def update
    if @post.update_attributes params[:post]
      flash[:notice] = 'Successfully updated'
      redirect_to @post
    else
      flash[:error] = 'Update failed'
      render action: 'edit'
    end
  end

private

  def get_post
    @post = if admin?
      Post.find_by_permalink(params[:id]) || Post.find(params[:id])
    else
      Post.published.find_by_permalink(params[:id]) || Post.published.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    # given permalink "foo" a request for "foo.js" will land here
    if params[:id] =~ /(.+)\.(js)\z/
      request.format = $~[2].to_sym
      @post = Post.published.find_by_permalink($~[1]) || Post.published.find($~[1])
    end
    raise unless @post
  end

  def record_not_found
    if admin?
      flash[:notice] = 'Requested post not found: create it?'
      session[:new_post_params] = { title: params[:id], permalink: params[:id] }
      redirect_to new_post_path
    else
      super posts_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def comment_count number
    pluralizing_count number, 'comment'
  end
end

app/views/posts/_form.html.haml
= render 'shared/error_messages', model: post

= form_for post do |f|
  = f.text_field :title
  = f.text_field :permalink,    annotation: 'optional', required: false
  = f.text_area  :excerpt,      rows: 10, annotation: wikitext_cheatsheet
  = f.text_area  :body,         rows: 30, annotation: 'optional'
  = f.text_field :pending_tags, label: 'Tags'
  = f.check_box  :public
  = f.check_box  :accepts_comments
  = f.submit

- content_for :javascript do
  :javascript
    Wincent.Posts.init();

app/views/posts/_preview.html.haml
%h3=@post.title
=@post.excerpt.w :base_heading_level => 3
=@post.body.w :base_heading_level => 3

app/views/posts/destroy.js.erb
$('#post_<%= @post.id %>').fadeOut('slow');

app/views/posts/edit.html.haml
- @page_title = 'Edit post'
= breadcrumbs link_to('Blog', posts_path), @page_title
%h1.major= @page_title
= render 'form', post: @post
%h2#preview_link.major Preview
-# TODO: graceful non-JS fallback
#ajax-flash
#preview= render 'preview'
.links
  = link_to 'posts index', posts_path
  = link_to 'show', post_path(@post)
- content_for :javascript do
  :javascript
    Wincent.Ajax.observeField({ 'kind': 'post', 'fieldName': 'title', 'include': ['excerpt', 'body'], 'url': '#{posts_path}' });
    Wincent.Ajax.observeField({ 'kind': 'post', 'fieldName': 'excerpt', 'include': ['title', 'body'], 'url': '#{posts_path}' });
    Wincent.Ajax.observeField({ 'kind': 'post', 'fieldName': 'body', 'include': ['title', 'excerpt'], 'url': '#{posts_path}' });
    Wincent.Ajax.setupPreviewLink({ 'kind': 'post', 'include': ['body', 'title', 'excerpt'], 'url': '#{posts_path}' });

app/views/posts/index.html.haml
-@page_title = 'blog index'
=breadcrumbs 'Blog'
#posts
  -@posts.each do |post|
    .post
      %h2.major=link_to post.title, post_path(post)
      .when
        =timeinfo post
        by
        =mail_to APP_CONFIG['admin_email'], APP_CONFIG['admin_name']
      =post.excerpt.w :base_heading_level => 2
      -unless post.body.blank?
        =link_to 'more...', post_path(post, :anchor => 'body')
      .info
        -# BUG: comment count is inaccurate here (includes non-public comments and
        -#      comments awaiting moderation), but we can't do an actual query here
        -#      (such as comments.published.count) without running into N+1
        -#      select problems; see lib/commentable for some notes on how we might
        -#      be able to implement a custom counter cache to work around this
        -#      problem
        - if post.accepts_comments? || post.comments_count > 0
          = link_to comment_count(post.comments_count),
              post_path(post, anchor: 'comments'), class: 'comments-link'
        = link_to icon('tags'), tags_path, class: 'tags-link'
        = tag_links(post)
  =@paginator.pagination_links if @paginator

app/views/posts/new.html.haml
- @page_title = 'New post'
= breadcrumbs link_to('Blog', posts_path), @page_title
%h1.major= @page_title
= render 'form', post: @post
%h2#preview_link.major Preview
-# TODO: graceful non-JS fallback
#ajax-flash
#preview= render 'preview'
.links= link_to 'all posts', posts_path
- content_for :javascript do
  :javascript
    Wincent.Ajax.observeField({ 'kind': 'post', 'fieldName': 'title', 'include': ['excerpt', 'body'], 'url': '#{posts_path}' });
    Wincent.Ajax.observeField({ 'kind': 'post', 'fieldName': 'excerpt', 'include': ['title', 'body'], 'url': '#{posts_path}' });
    Wincent.Ajax.observeField({ 'kind': 'post', 'fieldName': 'body', 'include': ['title', 'excerpt'], 'url': '#{posts_path}' });
    Wincent.Ajax.setupPreviewLink({ 'kind': 'post', 'include': ['body', 'title', 'excerpt'], 'url': '#{posts_path}' });

app/views/posts/show.html.haml
=breadcrumbs link_to('Blog', posts_path), @post.title
.post
  -@page_title = @post.title
  %h1.major=@post.title
  .when
    =timeinfo @post
    by
    =mail_to APP_CONFIG['admin_email'], APP_CONFIG['admin_name']
  .excerpt=@post.excerpt.w :base_heading_level => 1
  #body=@post.body.w :base_heading_level => 1
= render 'shared/tags', taggable: @post
-if @post.accepts_comments? || @post.comments_count != 0
  -# TODO: likely able to extract this into a shared partial
  %h3.major Comments
  %ol#comments.boxed
    =render @comments
  %h4.major Add a comment
  %p
    Comments are now closed for this post.