config/routes.rb
Wincent::Application.routes.draw do
  get ':id',
    id: ShortLink::SHORT_LINK_REGEX,
    constraints: { domain: APP_CONFIG['short_link_host'] },
    to: 'short_links#show'

  # must explicitly allow period in the id part of the route
  # otherwise it will be classified as a route separator
  resources :articles, id: /[^\/]+/ , path: 'wiki' do
    collection do
      get 'page/:page' => 'articles#index', :page => %r{\d+}
    end
  end

  resources :comments, except: %i[create new update]

  resources :links

  # must explicitly allow period in the id part of the route otherwise it
  # will be classified as a route separator
  resources :posts, path: 'blog', id: /[a-z0-9\-\.]+/ do
    collection do
      get 'page/:page' => 'posts#index', :page => %r{\d+}
    end
  end

  get 'repos', to: redirect('https://github.com/wincent')
  get 'repos/*rest', to: redirect('https://github.com/wincent')

  resources :resets
  resources :sessions, only: %i[new create destroy]

  resources :snippets do
    collection do
      get 'page/:page' => 'snippets#index', :page => %r{\d+}
    end
  end

  resources :taggings

  # must explicitly allow period in the id part of the route otherwise
  # it will be classified as a route separator
  resources :tags, id: /[a-z0-9\.]+/ do
    collection do
      get :search
    end
  end

  get 'twitter', to: redirect(APP_CONFIG['twitter_url'])
  get 'twitter/*rest', to: redirect(APP_CONFIG['twitter_url'])

  resources :users, only: %i[index show] do
    resources :emails, id: /[^\/]+/
  end

  get 'dashboard', to: redirect('/')
  get 'heartbeat/ping'

  get 'l/:id'           => 'links#show'
  get 'login'           => 'sessions#new'
  get 'logout'          => 'sessions#destroy'
  get 'misc/:action'    => 'misc'
  get 'search', to: redirect('https://www.google.com/#q=site:wincent.com')
  get 'support', to: redirect('/issues')

  root :to => 'posts#index'
end

app/views/layouts/application.haml
!!! 5
%html(lang='en-US')
  %head
    %meta(http-equiv='Content-Type' content='text/html;charset=UTF-8')
    %meta(name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no')
    = csrf_meta_tags
    %title
      = @page_title.presence || controller.controller_name
      &middot; wincent.com
    = stylesheet_link_tag 'application'
    = render 'shared/google_analytics'
  %body
    .viewport.menu-closed
      .app
        = named_anchor 'top'
        %nav.global
          %a.menu-icon(href='#') &equiv;
          %h1= link_to 'Wincent', root_path
          %ul.navbar-links
            %li{ class: navbar_selected?('products') }
              = link_to 'Products', '/products'
            %li{ class: navbar_selected?('blog') }= link_to 'Blog', posts_path
            %li{ class: navbar_selected?('wiki') }= link_to 'Wiki', articles_path
            %li{ class: navbar_selected?('issues') }= link_to 'Issues', '/issues'
        #content-wrapper
          #content
            - Array(flash[:notice]).each do |message|
              .notice
                %i.fa.fa-info-circle
                = raw message
            - Array(flash[:error]).each do |message|
              .error
                %i.fa.fa-exclamation-circle
                = raw message

            -# BUG: this is a bit of kludge so that we don't have to define a
            -# separate layout just to get breadcrumbs on our wikitext pages
            -# handled by the "misc" controller
            - if controller.kind_of? MiscController
              = breadcrumbs params[:action].capitalize
            = yield
        %footer.global
          %ul
            %li= mail_to APP_CONFIG['admin_email'], 'contact',
              title: "Email me at #{APP_CONFIG['admin_email']}",
              class: 'mailto'
            %li= link_to 'legal', '/misc/legal'
      .menu.hide
        .menu-inner
          %section
            %h2 Menu
            %ul
              %li= link_to 'Blog', posts_path
              %li= link_to 'Wiki', articles_path
              %li= link_to 'Issues', '/issues'
              %li= link_to 'Snippets', snippets_path

    -# TODO: think about doing something like this: https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/
    = javascript_include_tag 'application'#, async: true
    -# will need this to be queued
    = yield :javascript
    :javascript
      new Wincent.Menu();

app/views/layouts/empty.haml
!!!
%html{html_attrs}
  %head
    %meta(http-equiv='Content-Type' content='text/html;charset=UTF-8')
    %title wincent.com
    = stylesheet_link_tag 'application'
    = render 'shared/google_analytics'
  %body
    #content-wrapper
      #content
        = yield

app/views/layouts/static.haml
!!! 5
%html(lang='en-US')
  %head
    %meta(http-equiv='Content-Type' content='text/html;charset=UTF-8')
    %title
      = yield :title
      &middot; wincent.com
    %link(href='/assets/application-dfd4c4823a8b2979d87ab2ce01a9114c.css' rel='stylesheet' type='text/css' media='screen')
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35574060-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
  %body
    %nav.global
      %h1
        %a(href='/') Wincent
    #content-wrapper
      #content
        =yield
    %footer.global
      %ul
        %li
          %a.mailto(href='mailto:greg@hurrell.net' title='Email me at greg@hurrell.net') contact
        %li
          %a(href='/misc/legal') legal